---
- name: install httpd
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - httpd-devel

- name: copy config file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify: start httpd
